#! /usr/bin/env python3
"""HOMEINFO Digital Signage Linux setup

Usage:
    hi_setup (<ids> | --cid=<cid> --tid=<tid>) --image=<image_type> \
--hardware=<hw_type>

Options:
    -h --help           Show this page.
    -v --version        Show version.
    --user=<user_name>  Specifies the setup user's name.
    --passwd=<passwd>   Specifies the setup user's password.
"""

from docopt import docopt
from sys import stderr
from getpass import getpass
from hashlib import sha256
from requests import get
from homeinfo.lib.strf import Terminal
from os import listdir
from os.path import isdir, join

options = docopt(__doc__)
valid_ids_formats = ['<tid>.<cid>', '<cid>/<tid>']
image_dir = '/usr/local/share/homeinfo/images'
valid_hardware = ['amd', 'intel']
api_url = 'https://tls.homeinfo.de/termgr/setup'

format_info = '\n'.join(['', '    Valid identifier formats are:']
                        + [''.join(['    * ', f]) for f in valid_ids_formats])
hardware_info = '\n'.join(['', '    Valid hardware selections are:']
                          + [''.join(['    * ', h]) for h in valid_hardware])


class InvalidUserName(Exception):
    pass


class WrongPassword(Exception):
    pass


class NotAllowed(Exception):
    pass


def fail(err, *msgs, exit_code=3):
    """Print message to stderr and exit"""
    print(Terminal.red(Terminal.bold(err)), *msgs, file=stderr)
    exit(exit_code)


def sha256sum(s):
    """Creates a SHA-256 checksum of a string"""
    return str(sha256(s.encode()).hexdigest())


def list_images():
    """List available disk images"""
    for inode in listdir(image_dir):
        if isdir(join(image_dir, inode)):
            yield inode


def contact_api(user_name, passwd, action, cid=None, tid=None):
    """Contact the API with the respective
    user name, password and action call
    """
    params = {'user_name': user_name,
              'passwd': passwd,
              'action': action}
    if cid is not None:
        params['cid'] = str(cid)
    if tid is not None:
        params['tid'] = str(tid)
    return get(api_url, params=params)


def verify_cred(user_name, passwd):
    """Verify user name and password"""
    result = contact_api(user_name, passwd, action='credv')
    if result == '0':
        return True
    elif result == '1':
        raise InvalidUserName()
    elif result == '2':
        raise WrongPassword()
    else:
        fail('Unexpected return value from API')


def install_img(image, hardware):
    """Installs an image for the specified hardware type"""
    # TODO: Implement
    pass


def configure_system(cid, tid, config_data):
    """Configures the system for the respective customer
    and terminal ID with the provided configuration data
    """
    # TODO: Implement
    pass


if __name__ == '__main__':
    user_name = options['--user']
    passwd = options['--passwd']
    if not user_name:
        user_name = input('User name: ')
    if not passwd:
        passwd = sha256sum(getpass('Password: '))
    try:
        verify_cred(user_name, passwd)
    except InvalidUserName:
        fail('Invalid user name:', user_name)
    except WrongPassword:
        fail('Wrong password')
    ids = options['<ids>']
    cid = options['--cid']
    tid = options['--tid']
    image = options['--image']
    hardware = options['--hardware']

    if ids:
        if '.' in ids:
            try:
                tid, cid = ids.split('.')
            except ValueError:
                fail('Invalid identifier format:', ids, format_info)
        elif '/' in ids:
            try:
                cid, tid = ids.split('/')
            except ValueError:
                fail('Invalid identifier format:', ids, format_info)
        else:
            fail('Invalid identifier format:', ids, format_info)
    try:
        cid = int(cid)
    except (TypeError, ValueError):
        fail('Customer ID must be an integer')
    try:
        tid = int(tid)
    except (TypeError, ValueError):
        fail('Terminal ID must be an integer')
    if image not in list_images():
        image_info = '\n'.join(['', '    Valid image selections are:']
                               + [''.join(['    * ', s]) for
                                  s in list_images()])
        fail('Invalid image selection:', image, image_info)
    if hardware not in valid_hardware:
        fail('Invalid image selection:', image, hardware_info)
    if install_img(image, hardware):
        print('Installation of image succeeded')
    else:
        fail('Installation of image failed')
    if configure_system(cid, tid, hardware):
        print('Installation of image succeeded')
    else:
        fail('Configuration of system failed')
    exit(0)
