#! /bin/bash

_USER="hidslcfg"
_HOME="/home/${_USER}"

_add_user() {
    local COMMENT="HOMEINFO Digital Sigange Linux Configuration user"

    /usr/bin/id ${_USER} &> /dev/null || /usr/bin/useradd -mUd ${_HOME} -c "${COMMENT}" ${_USER}
}

_chown_home() {
    /usr/bin/chown -R ${_USER}.${_USER} "${_HOME}"
}

pre_install() {
    _add_user
}

pre_upgrade() {
    _add_user
}

post_install() {
    _chown_home
}

post_upgrade() {
    _chown_home
}