#! /usr/bin/env python3
"""HOMEINFO Digital Signage Linux resetter."""

from argparse import ArgumentParser
from logging import DEBUG, INFO, basicConfig
from os import geteuid

from hidslcfg.exceptions import ProgramError
from hidslcfg.globals import LOG_FORMAT
from hidslcfg.reset import reset
from hidslcfg.system import ProgramErrorHandler


DESCRIPTION = 'HOMEINFO Digital Signage Linux resetter.'


def get_args():
    """Parses the arguments."""

    parser = ArgumentParser(description=DESCRIPTION)
    parser.add_argument(
        '-v', '--verbose', action='store_true', help='be gassy')
    return parser.parse_args()


def main():
    """Runs the HIDSL reset."""

    if geteuid() != 0:
        raise ProgramError('You need to be root to run this script!')

    args = get_args()
    basicConfig(level=DEBUG if args.verbose else INFO, format=LOG_FORMAT)

    try:
        reset()
    except KeyboardInterrupt:
        print()
        raise ProgramError('Reset aborted by user.')


if __name__ == '__main__':
    with ProgramErrorHandler():
        main()
