#! /usr/bin/env python3
"""HOMEINFO Digital Signage Linux configurator.

Maintainer: Richard Neumann <r.neumann@homeinfo.de>

Usage:
    hidslcfg <ident> [options]
    hidslcfg [--tid=<terminal_id>] [--cid=<customer_id>] [options]

Options:
    --tid=<terminal_id>, -t     Specifies the physical terminal ID.
    --cid=<customer_id>, -c     Specifies the customer identifier.
    --user=<user_name>, -u      Specifies the setup user's name.
    --serial-number=<sn>, -s    Specifies the device's serial number.
    --no-serial-number, -n      Do not prompt for a serial number.
    --grace-time=<seconds>, -g  Specifies the grace time to wait for the
                                OpenVPN connection [default: 3].
    --verbose, -v               Be gassy.
    --help, -h                  Show this page.
"""
from getpass import getpass

from docopt import docopt

from hidslcfg.api import Client
from hidslcfg.configure import confirm_terminal, configure
from hidslcfg.exceptions import ProgramError
from hidslcfg.globals import OPTIONS
from hidslcfg.system import ProgramErrorHandler
from hidslcfg.termio import read_serial_number


def get_serial_number(options):
    """Returns the respective serial number."""

    serial_number = options['--serial-number']

    if serial_number is None and not options['--no-serial-number']:
        return read_serial_number()

    return serial_number


def get_gracetime(options):
    """Reads the respective grace time from the options."""

    try:
        return int(options['--grace-time'])
    except ValueError:
        raise ProgramError('Invalid value for grace time.')


def main(options):
    """Runs the HIDSL configurations."""

    OPTIONS['verbose'] = options['--verbose']
    ident = options['<ident>']

    if ident is None:
        tid = options['--tid']
        cid = options['--cid']
    else:
        try:
            tid, cid = ident.split('.')
        except ValueError:
            raise ProgramError(
                'INVALID IDENT', 'Identifier must be like <tid>.<cid>')

    user = options['--user']
    serial_number = get_serial_number(options)
    gracetime = get_gracetime(options)

    try:
        if cid is None:
            cid = input('Customer ID: ')
        if tid is None:
            tid = input('Terminal ID: ')
        if user is None:
            user = input('User name: ')

        passwd = getpass('Password: ')
    except EOFError:
        print()
        raise ProgramError('Missing mandatory data.')
    except KeyboardInterrupt:
        print()
        raise ProgramError('Configuration aborted by user.')

    with Client(user, passwd, cid, tid) as client:
        confirm_terminal(client.terminal, serial_number=serial_number)

        if serial_number is not None:
            if serial_number:
                print(f'Setting serial number of {tid}.{cid} to '
                      f'"{serial_number}".')
            else:
                print(f'Deleting serial number of {tid}.{cid}.')

            client.set_serial_number(serial_number)

        configure(tid, cid, client.vpndata, gracetime=gracetime)


if __name__ == '__main__':
    with ProgramErrorHandler():
        main(docopt(__doc__))
