echo -e "Welcome to the \033[1mHOMEINFO Digital Signage Linux\033[0m configuration"
echo
echo -e "Run \033[1msudo hidslcfg\033[0m to perform the setup"
echo
echo -e "For usage instructions run \033[1mhidslcfg --help\033[0m"
echo
alias hidslcfg="sudo /usr/bin/hidslcfg"
alias hidslreset="sudo /usr/bin/hidslreset"
