#! /usr/bin/env python3
"""HOMEINFO Digital Signage Linux resetter.

Maintainer: Richard Neumann <r.neumann@homeinfo.de>

Usage:
    hidslreset [options]

Options:
    --verbose               Be gassy.
    -h --help               Show this page.
"""
from os import geteuid

from docopt import docopt

from hidslcfg import OPTIONS, reset


def main(options):
    """Runs the HIDSL reset."""

    if geteuid() != 0:
        raise ProgramError('You need to be root to run this script!')

    OPTIONS['verbose'] = options['--verbose']

    try:
        reset()
    except KeyboardInterrupt:
        print()
        raise ProgramError('Reset aborted by user.')


if __name__ == '__main__':
    with ProgramErrorHandler():
        main(docopt(__doc__))

