#! /usr/bin/env python3
"""HOMEINFO Digital Signage Linux configurator

Maintainer: Richard Neumann <r.neumann@homeinfo.de>

Usage:
    hidslcfg <ident> [--user=<user_name>] [--verbose]
    hidslcfg [options]
    hidslreset

Options:
    --tid=<terminal_id>  Specifies the physical terminal identifier
    --cid=<customer_id>  Specifies the customer identifier
    --user=<user_name>   Specifies the setup user's name
    --verbose            Be gassy
    -h --help            Show this page
"""

from sys import stderr
from os import chdir, geteuid
from os.path import join, basename
from getpass import getpass
from shutil import rmtree
from tempfile import mkdtemp
from subprocess import run, CalledProcessError, DEVNULL
from contextlib import suppress
from time import sleep

from docopt import docopt
from requests import get


__all__ = ['InvalidCredentials', 'Unauthorized', 'APIError',
           'OutsideOfWithStatement', 'fail', 'TerminalAddress', 'APIClient',
           'Configurator']

SCRIPTS = {
    # hidslcfg
    'hidslcfg': """HOMEINFO Digital Signage Linux configurator

Maintainer: Richard Neumann <r.neumann@homeinfo.de>

Usage:
    hidslcfg <ident> [--user=<user_name>] [--verbose]
    hidslcfg [options]

Options:
    --tid=<terminal_id>  Specifies the physical terminal identifier
    --cid=<customer_id>  Specifies the customer identifier
    --user=<user_name>   Specifies the setup user's name
    --verbose            Be gassy
    -h --help            Show this page""",
    # hidslreset
    'hidslreset': """HOMEINFO Digital Signage Linux resetter

Maintainer: Richard Neumann <r.neumann@homeinfo.de>

Usage:
    hidslreset

Options:
    --verbose            Be gassy
    -h --help            Show this page"""}

INVALID_SCRIPT = 'Script name "{0}" is invalid'

VERBOSE = False

PACMAN_CONF_SRC = 'pacman.conf'
PACMAN_CONF_DST = '/etc/pacman.conf'
PACMAN_CONF_BAK = '/etc/.pacman.conf.bak'
VPN_ARCHIVE = 'openvpn.tar.gz'
HOSTNAME_FILE_SRC = 'hostname'
HOSTNAME_FILE_DST = '/etc/hostname'

PACMAN_INST = '/usr/bin/install -o root -g root -m 644 -T {src} {dst}'
VPN_INST = '/usr/bin/tar xf {arch} -C /etc/openvpn'
HOSTNAME_INST = '/usr/bin/install -o root -g root -m 644 -T {src} {dst}'

DIGSIG_TARGET = 'digital-signage.target'
CONFIG_TARGET = 'hidslcfg.target'
SYSTEMD_CMD = '/usr/bin/systemctl set-default {target}'

VPN_CMD = '/usr/bin/systemctl restart openvpn@{instance}.service'
VPN_CONFIG = 'terminals'

PING_CMD = '/usr/bin/ping -W 1 -c 5 {host}'
VPN_SERVER = '10.8.0.1'


class InvalidCredentials(Exception):
    """Indicates invalid credentials"""
    pass


class Unauthorized(Exception):
    """Indicates that the user is not allowed
    to setup the respective terminal
    """
    pass


class ErrorMessage(Exception):
    """Raisable error message"""

    def __init__(self, msg):
        """Sets the text"""
        super().__init__()
        self._msg = msg

    def __str__(self):
        """Returns the message"""
        return self._msg


class APIError(ErrorMessage):
    """Indicates a user error"""

    pass


class OutsideOfWithStatement(ErrorMessage):
    """Indicates that an operation that requires being
    within a with statement was executed outside of it
    """

    pass


def fail(err, *msgs, exit_code=3):
    """Print message to stderr and exit"""
    print('\033[91m\033[1m', end='', file=stderr)  # Red and bold
    print(err, end='', file=stderr)
    print('\033[0m', end=' ', file=stderr)
    print(*msgs, file=stderr)
    exit(exit_code)


def sudo(cmd):
    """Run a command as root using sudo"""
    output = None if VERBOSE else DEVNULL
    result = run(
        '/usr/bin/sudo -n {cmd}'.format(cmd=cmd), shell=True,
        stdin=DEVNULL, stdout=output, stderr=output)
    result.check_returncode()


def getdata(tid, cid, user, passwd):
    """Get data from web API"""
    client = APIClient(user, passwd, cid, tid)
    try:
        location = client.location
        print('Determined terminal location:')
        print()
        print(location)
        print()
        yn = input('Is this correct? [y/N]: ')
        if yn.lower() in ['y', 'yes']:
            if VERBOSE:
                print('Retrieving OpenVPN data')
            else:
                print('Please wait...')
            vpndata = client.vpndata
            if VERBOSE:
                print('Retrieving pacman.conf')
            repoconf = client.repoconf
        else:
            fail('Setup aborted by user')
    except InvalidCredentials:
        fail('INVALID CREDENTIALS',
             'Your user name and / or password are incorrect')
    except Unauthorized:
        fail('UNAUTHORIZED',
             'You are not authorized to set up this terminal')
    except APIError as api_err:
        fail('WEB API ERROR', api_err)
    except KeyboardInterrupt:
        print()
        fail('Setup aborted by user')
    else:
        return (vpndata, repoconf)


def configure(tid, cid, vpndata, repoconf):
    """Performs the terminal configuration"""
    with Configurator(
            tid, cid, vpndata, repoconf) as configurator:
        if VERBOSE:
            print('Installing OpenVPN configuration')
        try:
            configurator.configure_openvpn()
        except CalledProcessError:
            fail('SUBPROCESS ERROR',
                 'Installation of OpenVPN configuration failed')
        if VERBOSE:
            print('Restarting OpenVPN')
        try:
            configurator.restart_vpn()
        except CalledProcessError:
            fail('SUBPROCESS ERROR',
                 'Restart of OpenVPN server failed')
        if VERBOSE:
            print('Waiting for OpenVPN server to start')
        sleep(3)
        if VERBOSE:
            print('Checking OpenVPN connection')
        try:
            configurator.test_vpn()
        except CalledProcessError:
            fail('SUBPROCESS ERROR',
                 'Cannot contact OpenVPN server')
        if VERBOSE:
            print('Installing /etc/pacman.conf')
        try:
            configurator.configure_pacman()
        except CalledProcessError:
            fail('SUBPROCESS ERROR',
                 'Installation of /etc/pacman.conf failed')
            print('Installing /etc/hostname')
        try:
            configurator.configure_hostname()
        except CalledProcessError:
            fail('SUBPROCESS ERROR',
                 'Installation of /etc/hostname failed')
        if VERBOSE:
            print('Setting systemd target to digital signage')
        try:
            configurator.set_systemd_target()
        except CalledProcessError:
            fail('SUBPROCESS ERROR',
                 'Setting of systemd target failed')
        print()
        print('Setup completed successfully')
        try:
            yn = input('Do you want to reboot now? [y/N]: ')
        except KeyboardInterrupt:
            print()
            reboot = False
        else:
            reboot = yn.lower() in ['y', 'yes']
        if reboot:
            run('/usr/bin/sudo -n /usr/bin/reboot', shell=True)
        else:
            print('Okay, not rebooting',
                  'You can reboot any time by pressing',
                  '[CTRL]+[ALT]+[DEL]', sep='\n')
            exit(0)


def reset():
    """Resets the system's configuration"""
    reset_commands = {
        'Reset hostname': '/usr/bin/rm /etc/hostname',
        'Remove digital signage data': '/usr/bin/rm -R /var/cache/digsig/*',
        'Remove OpenVPN configuration': '/usr/bin/rm -R /etc/openvpn/*',
        'Reset systemd.target': SYSTEMD_CMD.format(target=DIGSIG_TARGET)}
    for reset_command in reset_commands:
        cmd = reset_commands[reset_command]
        try:
            self.sudo(cmd)
        except CalledProcessError as cpe:
            fail('Could not {0}'.format(reset_command))


class TerminalAddress():
    """Terminal address data container"""

    MAIN_SEP = ', '
    SUB_SEP = ' '

    def __init__(self, s):
        """Generate terminal address from a string"""
        street_houseno, zip_city = s.split(self.MAIN_SEP)
        *street, self.houseno = street_houseno.split(self.SUB_SEP)
        self.street = self.SUB_SEP.join(street)
        self.zip, *city = zip_city.split(self.SUB_SEP)
        self.city = self.SUB_SEP.join(city)

    def __str__(self):
        """Converts the address into a human readable form"""
        return ('Street:        {street}\n'
                'House number:  {houseno}\n'
                'ZIP code:      {zip}\n'
                'City:          {city}').format(
            street=self.street, houseno=self.houseno,
            zip=self.zip, city=self.city)


class APIClient():
    """Class to retrieve data from the web API"""

    PROTO = 'https'
    HOST = 'tls.homeinfo.de'
    PATH = '/termgr/setup'

    def __init__(self, user, passwd, cid, tid):
        """Initialize with credentials"""
        self.user = user
        self.passwd = passwd
        self.cid = cid
        self.tid = tid

    def __call__(self):
        """Get configuration data"""
        return (self.vpndata, self.repoconf)

    @property
    def valid(self):
        """Verifies the set credentials"""
        status_code, text = self.apicall('verify')
        if status_code == 200:
            return True
        elif status_code == 401:
            if text == 'Invalid credentials':
                raise InvalidCredentials()
            else:
                raise Unauthorized()
        else:
            raise APIError(text)

    @property
    def location(self):
        """Gets the terminal location"""
        reply = self.apicall('location')
        return TerminalAddress(reply.text)

    @property
    def vpndata(self):
        """Gets the terminal's VPN keys and configuration"""
        reply = self.apicall('vpn_data')
        return reply.content

    @property
    def repoconf(self):
        """Returns the pacman.conf"""
        reply = self.apicall('repo_config')
        return reply.text

    @property
    def url(self):
        """Reutrns the API URL"""
        return '{proto}://{host}{path}'.format(
            proto=self.PROTO, host=self.HOST, path=self.PATH)

    def apicall(self, action):
        """Contact the API with the respective
        user name, password and action call
        """
        params = {
            'user_name': self.user,
            'passwd': self.passwd,
            'action': action,
            'cid': self.cid,
            'tid': self.tid}
        reply = get(self.url, params=params)
        status_code = reply.status_code
        if status_code == 200:
            return reply
        elif status_code == 401:
            if reply.text == 'Invalid credentials':
                raise InvalidCredentials()
            else:
                raise Unauthorized()
        else:
            raise APIError(reply.text)


class Configurator():
    """Terminal configurator"""

    def __init__(self, tid, cid, vpndata, repoconf):
        """Sets VPN configuration and repository configuration"""
        self.tid = tid
        self.cid = cid
        self.vpndata = vpndata
        self.repoconf = repoconf
        self._tmpdir = None

    def __enter__(self):
        self._tmpdir = mkdtemp()
        pacmanconf_path = join(self._tmpdir, PACMAN_CONF_SRC)
        vpndata_path = join(self._tmpdir, VPN_ARCHIVE)
        with open(pacmanconf_path, 'w') as pacmanconf_file:
            pacmanconf_file.write(repoconf)
        with open(vpndata_path, 'wb') as vpndata_file:
            vpndata_file.write(self.vpndata)
        return self

    def __exit__(self, *_):
        rmtree(self._tmpdir)
        self._tmpdir = None

    def configure_pacman(self):
        """Install /etc/pacman.conf"""
        if self._tmpdir is not None:
            chdir(self._tmpdir)
            cmd = PACMAN_INST.format(
                src=PACMAN_CONF_SRC, dst=PACMAN_CONF_DST)
            sudo(cmd)
        else:
            raise OutsideOfWithStatement('Not within with statement')

    def configure_openvpn(self):
        """Install OpenVPN configuration"""
        if self._tmpdir is not None:
            # Clean up OpenVPN config
            with suppress(CalledProcessError):
                sudo('/usr/bin/rm /etc/openvpn/*')
            # Unpack OpenVPN archive
            chdir(self._tmpdir)
            cmd = VPN_INST.format(arch=VPN_ARCHIVE)
            sudo(cmd)
        else:
            raise OutsideOfWithStatement('Not within with statement')

    def restart_vpn(self):
        """Set systemd default target to digital-signage.target"""
        cmd = VPN_CMD.format(instance=VPN_CONFIG)
        sudo(cmd)

    def test_vpn(self):
        """Set systemd default target to digital-signage.target"""
        output = None if VERBOSE else DEVNULL
        result = run(
            PING_CMD.format(host=VPN_SERVER), shell=True,
            stdin=DEVNULL, stdout=output, stderr=output)
        result.check_returncode()

    def configure_hostname(self):
        """Configure /etc/hostname"""
        if self._tmpdir is not None:
            chdir(self._tmpdir)
            hostname = '{tid}.{cid}'.format(tid=self.tid, cid=self.cid)
            with open(HOSTNAME_FILE_SRC, 'w') as hostname_tmp:
                hostname_tmp.write(hostname)
            cmd = HOSTNAME_INST.format(
                src=HOSTNAME_FILE_SRC, dst=HOSTNAME_FILE_DST)
            sudo(cmd)
        else:
            raise OutsideOfWithStatement('Not within with statement')

    def set_systemd_target(self):
        """Set systemd default target to digital-signage.target"""
        cmd = SYSTEMD_CMD.format(target=DIGSIG_TARGET)
        sudo(cmd)


if __name__ == '__main__':
    if geteuid() == 0:
        fail('Refusing to run as root!')
    else:
        script_name = basename(__file__)
        try:
            doc = SCRIPTS[script_name]
        except KeyError:
            fail(INVALID_SCRIPT.format(script_name))
        else:
            options = docopt(doc)
            VERBOSE = options['--verbose']
            if script_name == 'hidslcfg':
                # Validate options
                ident = options['<ident>']
                if ident is None:
                    tid = options['--tid']
                    cid = options['--cid']
                else:
                    try:
                        tid, cid = ident.split('.')
                    except ValueError:
                        fail('INVALID IDENT',
                             'Identifier must be like <tid>.<cid>')
                user = options['--user']
                try:
                    if cid is None:
                        cid = input('Customer ID: ')
                    if tid is None:
                        tid = input('Terminal ID: ')
                    if not user:
                        user = input('User name: ')
                    passwd = getpass('Password: ')
                except KeyboardInterrupt:
                    print()
                    fail('Setup aborted by user')
                else:
                    # Call API
                    try:
                        vpndata, repoconf = getdata(
                            tid, cid, user, passwd)
                    except ConnectionError:
                        fail('Cannot connect to webservice '
                             '- check your internet connection')
                    else:
                        # Configure system
                        configure(tid, cid, vpndata, repoconf)
            elif script_name == 'hidslreset':
                reset()
            else:
                fail(INVALID_SCRIPT.format(script_name))
